name: Upload .env to GitHub Secrets

on:
  workflow_dispatch:

jobs:
  upload-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install gh -y

    - name: Authenticate with GitHub CLI
      run: echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token

    - name: Upload .env secrets to GitHub
      run: |
        while IFS='=' read -r key value
        do
          if [[ ! -z "$key" ]]; then
            gh secret set "$key" --body "$value"
          fi
        done < .env
