name: Upload .env to GitHub Secrets

on:
  workflow_dispatch:

jobs:
  upload-secrets:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub CLI
        run: echo "$GH_TOKEN" | gh auth login --with-token

      - name: Upload .env to secrets
        run: |
          while IFS='=' read -r key value || [[ -n "$key" ]]; do
            if [[ "$key" != \#* && -n "$key" && -n "$value" ]]; then
              echo "Uploading $key..."
              gh secret set "$key" --body "$value"
            fi
          done < .env
