name: Upload secrets from .env

on:
  workflow_dispatch:

jobs:
  upload-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (اختياري)
        uses: actions/checkout@v4

      - name: Upload secrets using REST API
        run: |
          echo "Reading .env and sending secrets to GitHub..."

          while IFS='=' read -r key value; do
            if [[ ! "$key" =~ ^# && -n "$key" ]]; then
              # Trim quotes if exist
              clean_value=$(echo "$value" | sed -e 's/^["'\'']//;s/["'\'']$//')

              # Encrypt the value using GitHub's public key
              REPO="اسم_المستخدم/اسم_الريبو"
              GH_API="https://api.github.com"
              GH_TOKEN="${{ secrets.GH_PAT }}"

              pubkey_response=$(curl -s -H "Authorization: token $GH_TOKEN" \
                "$GH_API/repos/$REPO/actions/secrets/public-key")

              key_id=$(echo "$pubkey_response" | jq -r .key_id)
              pubkey=$(echo "$pubkey_response" | jq -r .key)

              encrypted_value=$(echo -n "$clean_value" | \
                openssl rsautl -encrypt -pubin -inkey <(echo "$pubkey" | base64 -d) | base64)

              curl -s -X PUT "$GH_API/repos/$REPO/actions/secrets/$key" \
                -H "Authorization: token $GH_TOKEN" \
                -H "Content-Type: application/json" \
                -d "{\"encrypted_value\":\"$encrypted_value\",\"key_id\":\"$key_id\"}"

              echo "✅ Secret $key uploaded."
            fi
          done < .env
