name: Upload .env to GitHub Secrets (via gh CLI)

on:
  workflow_dispatch:

jobs:
  upload-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Login to GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "$GH_TOKEN" | gh auth login --with-token

      - name: Upload secrets from .env
        run: |
          while IFS='=' read -r key value; do
            if [[ ! "$key" =~ ^# && -n "$key" ]]; then
              echo "Uploading $key..."
              gh secret set "$key" --body "$value"
            fi
          done < .env
